/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator.index'
import { Route as CoordinatorEvidenceRouteImport } from './routes/coordinator.evidence'
import { Route as CoordinatorTestsRouteImport } from './routes/coordinator.tests'
import { Route as HistoryBeforeDeleteShareRouteImport } from './routes/history.before-delete-share'
import { Route as IndexBeforeCleanHotelIntroRouteImport } from './routes/index.before-clean-hotel-intro'
import { Route as IndexBeforeGeneralSidebarRouteImport } from './routes/index.before-general-sidebar'
import { Route as IndexBeforeHotelConversationRouteImport } from './routes/index.before-hotel-conversation'
import { Route as IndexBeforeHotelFinalRouteImport } from './routes/index.before-hotel-final'
import { Route as IndexBeforeHotelFinal2RouteImport } from './routes/index.before-hotel-final-2'
import { Route as IndexBeforeHotelFinalFixRouteImport } from './routes/index.before-hotel-final-fix'
import { Route as IndexBeforeHotelImageFallbackRouteImport } from './routes/index.before-hotel-image-fallback'
import { Route as IndexBeforeHotelIntroRouteImport } from './routes/index.before-hotel-intro'
import { Route as IndexBeforeHotelOpenFinalRouteImport } from './routes/index.before-hotel-open-final'
import { Route as IndexBeforeHotelPanelRouteImport } from './routes/index.before-hotel-panel'
import { Route as IndexBeforeHotelResultsLiftRouteImport } from './routes/index.before-hotel-results-lift'
import { Route as IndexBeforeHotelSessionFinalWiringRouteImport } from './routes/index.before-hotel-session-final-wiring'
import { Route as IndexBeforeHotelSessionUiFinalRouteImport } from './routes/index.before-hotel-session-ui-final'
import { Route as IndexBeforeHotelSessionWiringRouteImport } from './routes/index.before-hotel-session-wiring'
import { Route as IndexBeforeHotelTimerFixRouteImport } from './routes/index.before-hotel-timer-fix'
import { Route as IndexBeforeHotelV2RouteImport } from './routes/index.before-hotel-v2'
import { Route as IndexBeforeHotelVoiceErrorFixRouteImport } from './routes/index.before-hotel-voice-error-fix'
import { Route as IndexBeforeSerpapiRouteImport } from './routes/index.before-serpapi'
import { Route as IndexBeforeSidebarEditRouteImport } from './routes/index.before-sidebar-edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorEvidenceRoute = CoordinatorEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorTestsRoute = CoordinatorTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => CoordinatorRoute,
} as any)
const HistoryBeforeDeleteShareRoute =
  HistoryBeforeDeleteShareRouteImport.update({
    id: '/before-delete-share',
    path: '/before-delete-share',
    getParentRoute: () => HistoryRoute,
  } as any)
const IndexBeforeCleanHotelIntroRoute =
  IndexBeforeCleanHotelIntroRouteImport.update({
    id: '/index/before-clean-hotel-intro',
    path: '/index/before-clean-hotel-intro',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeGeneralSidebarRoute =
  IndexBeforeGeneralSidebarRouteImport.update({
    id: '/index/before-general-sidebar',
    path: '/index/before-general-sidebar',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelConversationRoute =
  IndexBeforeHotelConversationRouteImport.update({
    id: '/index/before-hotel-conversation',
    path: '/index/before-hotel-conversation',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelFinalRoute = IndexBeforeHotelFinalRouteImport.update({
  id: '/index/before-hotel-final',
  path: '/index/before-hotel-final',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBeforeHotelFinal2Route = IndexBeforeHotelFinal2RouteImport.update({
  id: '/index/before-hotel-final-2',
  path: '/index/before-hotel-final-2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBeforeHotelFinalFixRoute =
  IndexBeforeHotelFinalFixRouteImport.update({
    id: '/index/before-hotel-final-fix',
    path: '/index/before-hotel-final-fix',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelImageFallbackRoute =
  IndexBeforeHotelImageFallbackRouteImport.update({
    id: '/index/before-hotel-image-fallback',
    path: '/index/before-hotel-image-fallback',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelIntroRoute = IndexBeforeHotelIntroRouteImport.update({
  id: '/index/before-hotel-intro',
  path: '/index/before-hotel-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBeforeHotelOpenFinalRoute =
  IndexBeforeHotelOpenFinalRouteImport.update({
    id: '/index/before-hotel-open-final',
    path: '/index/before-hotel-open-final',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelPanelRoute = IndexBeforeHotelPanelRouteImport.update({
  id: '/index/before-hotel-panel',
  path: '/index/before-hotel-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBeforeHotelResultsLiftRoute =
  IndexBeforeHotelResultsLiftRouteImport.update({
    id: '/index/before-hotel-results-lift',
    path: '/index/before-hotel-results-lift',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelSessionFinalWiringRoute =
  IndexBeforeHotelSessionFinalWiringRouteImport.update({
    id: '/index/before-hotel-session-final-wiring',
    path: '/index/before-hotel-session-final-wiring',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelSessionUiFinalRoute =
  IndexBeforeHotelSessionUiFinalRouteImport.update({
    id: '/index/before-hotel-session-ui-final',
    path: '/index/before-hotel-session-ui-final',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelSessionWiringRoute =
  IndexBeforeHotelSessionWiringRouteImport.update({
    id: '/index/before-hotel-session-wiring',
    path: '/index/before-hotel-session-wiring',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelTimerFixRoute =
  IndexBeforeHotelTimerFixRouteImport.update({
    id: '/index/before-hotel-timer-fix',
    path: '/index/before-hotel-timer-fix',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeHotelV2Route = IndexBeforeHotelV2RouteImport.update({
  id: '/index/before-hotel-v2',
  path: '/index/before-hotel-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBeforeHotelVoiceErrorFixRoute =
  IndexBeforeHotelVoiceErrorFixRouteImport.update({
    id: '/index/before-hotel-voice-error-fix',
    path: '/index/before-hotel-voice-error-fix',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexBeforeSerpapiRoute = IndexBeforeSerpapiRouteImport.update({
  id: '/index/before-serpapi',
  path: '/index/before-serpapi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexBeforeSidebarEditRoute = IndexBeforeSidebarEditRouteImport.update({
  id: '/index/before-sidebar-edit',
  path: '/index/before-sidebar-edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/coordinator/evidence': typeof CoordinatorEvidenceRoute
  '/coordinator/tests': typeof CoordinatorTestsRoute
  '/history/before-delete-share': typeof HistoryBeforeDeleteShareRoute
  '/index/before-clean-hotel-intro': typeof IndexBeforeCleanHotelIntroRoute
  '/index/before-general-sidebar': typeof IndexBeforeGeneralSidebarRoute
  '/index/before-hotel-conversation': typeof IndexBeforeHotelConversationRoute
  '/index/before-hotel-final': typeof IndexBeforeHotelFinalRoute
  '/index/before-hotel-final-2': typeof IndexBeforeHotelFinal2Route
  '/index/before-hotel-final-fix': typeof IndexBeforeHotelFinalFixRoute
  '/index/before-hotel-image-fallback': typeof IndexBeforeHotelImageFallbackRoute
  '/index/before-hotel-intro': typeof IndexBeforeHotelIntroRoute
  '/index/before-hotel-open-final': typeof IndexBeforeHotelOpenFinalRoute
  '/index/before-hotel-panel': typeof IndexBeforeHotelPanelRoute
  '/index/before-hotel-results-lift': typeof IndexBeforeHotelResultsLiftRoute
  '/index/before-hotel-session-final-wiring': typeof IndexBeforeHotelSessionFinalWiringRoute
  '/index/before-hotel-session-ui-final': typeof IndexBeforeHotelSessionUiFinalRoute
  '/index/before-hotel-session-wiring': typeof IndexBeforeHotelSessionWiringRoute
  '/index/before-hotel-timer-fix': typeof IndexBeforeHotelTimerFixRoute
  '/index/before-hotel-v2': typeof IndexBeforeHotelV2Route
  '/index/before-hotel-voice-error-fix': typeof IndexBeforeHotelVoiceErrorFixRoute
  '/index/before-serpapi': typeof IndexBeforeSerpapiRoute
  '/index/before-sidebar-edit': typeof IndexBeforeSidebarEditRoute
  '/coordinator/': typeof CoordinatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/coordinator/evidence': typeof CoordinatorEvidenceRoute
  '/coordinator/tests': typeof CoordinatorTestsRoute
  '/history/before-delete-share': typeof HistoryBeforeDeleteShareRoute
  '/index/before-clean-hotel-intro': typeof IndexBeforeCleanHotelIntroRoute
  '/index/before-general-sidebar': typeof IndexBeforeGeneralSidebarRoute
  '/index/before-hotel-conversation': typeof IndexBeforeHotelConversationRoute
  '/index/before-hotel-final': typeof IndexBeforeHotelFinalRoute
  '/index/before-hotel-final-2': typeof IndexBeforeHotelFinal2Route
  '/index/before-hotel-final-fix': typeof IndexBeforeHotelFinalFixRoute
  '/index/before-hotel-image-fallback': typeof IndexBeforeHotelImageFallbackRoute
  '/index/before-hotel-intro': typeof IndexBeforeHotelIntroRoute
  '/index/before-hotel-open-final': typeof IndexBeforeHotelOpenFinalRoute
  '/index/before-hotel-panel': typeof IndexBeforeHotelPanelRoute
  '/index/before-hotel-results-lift': typeof IndexBeforeHotelResultsLiftRoute
  '/index/before-hotel-session-final-wiring': typeof IndexBeforeHotelSessionFinalWiringRoute
  '/index/before-hotel-session-ui-final': typeof IndexBeforeHotelSessionUiFinalRoute
  '/index/before-hotel-session-wiring': typeof IndexBeforeHotelSessionWiringRoute
  '/index/before-hotel-timer-fix': typeof IndexBeforeHotelTimerFixRoute
  '/index/before-hotel-v2': typeof IndexBeforeHotelV2Route
  '/index/before-hotel-voice-error-fix': typeof IndexBeforeHotelVoiceErrorFixRoute
  '/index/before-serpapi': typeof IndexBeforeSerpapiRoute
  '/index/before-sidebar-edit': typeof IndexBeforeSidebarEditRoute
  '/coordinator': typeof CoordinatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/history': typeof HistoryRouteWithChildren
  '/settings': typeof SettingsRoute
  '/coordinator/evidence': typeof CoordinatorEvidenceRoute
  '/coordinator/tests': typeof CoordinatorTestsRoute
  '/history/before-delete-share': typeof HistoryBeforeDeleteShareRoute
  '/index/before-clean-hotel-intro': typeof IndexBeforeCleanHotelIntroRoute
  '/index/before-general-sidebar': typeof IndexBeforeGeneralSidebarRoute
  '/index/before-hotel-conversation': typeof IndexBeforeHotelConversationRoute
  '/index/before-hotel-final': typeof IndexBeforeHotelFinalRoute
  '/index/before-hotel-final-2': typeof IndexBeforeHotelFinal2Route
  '/index/before-hotel-final-fix': typeof IndexBeforeHotelFinalFixRoute
  '/index/before-hotel-image-fallback': typeof IndexBeforeHotelImageFallbackRoute
  '/index/before-hotel-intro': typeof IndexBeforeHotelIntroRoute
  '/index/before-hotel-open-final': typeof IndexBeforeHotelOpenFinalRoute
  '/index/before-hotel-panel': typeof IndexBeforeHotelPanelRoute
  '/index/before-hotel-results-lift': typeof IndexBeforeHotelResultsLiftRoute
  '/index/before-hotel-session-final-wiring': typeof IndexBeforeHotelSessionFinalWiringRoute
  '/index/before-hotel-session-ui-final': typeof IndexBeforeHotelSessionUiFinalRoute
  '/index/before-hotel-session-wiring': typeof IndexBeforeHotelSessionWiringRoute
  '/index/before-hotel-timer-fix': typeof IndexBeforeHotelTimerFixRoute
  '/index/before-hotel-v2': typeof IndexBeforeHotelV2Route
  '/index/before-hotel-voice-error-fix': typeof IndexBeforeHotelVoiceErrorFixRoute
  '/index/before-serpapi': typeof IndexBeforeSerpapiRoute
  '/index/before-sidebar-edit': typeof IndexBeforeSidebarEditRoute
  '/coordinator/': typeof CoordinatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coordinator'
    | '/history'
    | '/settings'
    | '/coordinator/evidence'
    | '/coordinator/tests'
    | '/history/before-delete-share'
    | '/index/before-clean-hotel-intro'
    | '/index/before-general-sidebar'
    | '/index/before-hotel-conversation'
    | '/index/before-hotel-final'
    | '/index/before-hotel-final-2'
    | '/index/before-hotel-final-fix'
    | '/index/before-hotel-image-fallback'
    | '/index/before-hotel-intro'
    | '/index/before-hotel-open-final'
    | '/index/before-hotel-panel'
    | '/index/before-hotel-results-lift'
    | '/index/before-hotel-session-final-wiring'
    | '/index/before-hotel-session-ui-final'
    | '/index/before-hotel-session-wiring'
    | '/index/before-hotel-timer-fix'
    | '/index/before-hotel-v2'
    | '/index/before-hotel-voice-error-fix'
    | '/index/before-serpapi'
    | '/index/before-sidebar-edit'
    | '/coordinator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/settings'
    | '/coordinator/evidence'
    | '/coordinator/tests'
    | '/history/before-delete-share'
    | '/index/before-clean-hotel-intro'
    | '/index/before-general-sidebar'
    | '/index/before-hotel-conversation'
    | '/index/before-hotel-final'
    | '/index/before-hotel-final-2'
    | '/index/before-hotel-final-fix'
    | '/index/before-hotel-image-fallback'
    | '/index/before-hotel-intro'
    | '/index/before-hotel-open-final'
    | '/index/before-hotel-panel'
    | '/index/before-hotel-results-lift'
    | '/index/before-hotel-session-final-wiring'
    | '/index/before-hotel-session-ui-final'
    | '/index/before-hotel-session-wiring'
    | '/index/before-hotel-timer-fix'
    | '/index/before-hotel-v2'
    | '/index/before-hotel-voice-error-fix'
    | '/index/before-serpapi'
    | '/index/before-sidebar-edit'
    | '/coordinator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coordinator'
    | '/history'
    | '/settings'
    | '/coordinator/evidence'
    | '/coordinator/tests'
    | '/history/before-delete-share'
    | '/index/before-clean-hotel-intro'
    | '/index/before-general-sidebar'
    | '/index/before-hotel-conversation'
    | '/index/before-hotel-final'
    | '/index/before-hotel-final-2'
    | '/index/before-hotel-final-fix'
    | '/index/before-hotel-image-fallback'
    | '/index/before-hotel-intro'
    | '/index/before-hotel-open-final'
    | '/index/before-hotel-panel'
    | '/index/before-hotel-results-lift'
    | '/index/before-hotel-session-final-wiring'
    | '/index/before-hotel-session-ui-final'
    | '/index/before-hotel-session-wiring'
    | '/index/before-hotel-timer-fix'
    | '/index/before-hotel-v2'
    | '/index/before-hotel-voice-error-fix'
    | '/index/before-serpapi'
    | '/index/before-sidebar-edit'
    | '/coordinator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoordinatorRoute: typeof CoordinatorRouteWithChildren
  HistoryRoute: typeof HistoryRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  IndexBeforeCleanHotelIntroRoute: typeof IndexBeforeCleanHotelIntroRoute
  IndexBeforeGeneralSidebarRoute: typeof IndexBeforeGeneralSidebarRoute
  IndexBeforeHotelConversationRoute: typeof IndexBeforeHotelConversationRoute
  IndexBeforeHotelFinalRoute: typeof IndexBeforeHotelFinalRoute
  IndexBeforeHotelFinal2Route: typeof IndexBeforeHotelFinal2Route
  IndexBeforeHotelFinalFixRoute: typeof IndexBeforeHotelFinalFixRoute
  IndexBeforeHotelImageFallbackRoute: typeof IndexBeforeHotelImageFallbackRoute
  IndexBeforeHotelIntroRoute: typeof IndexBeforeHotelIntroRoute
  IndexBeforeHotelOpenFinalRoute: typeof IndexBeforeHotelOpenFinalRoute
  IndexBeforeHotelPanelRoute: typeof IndexBeforeHotelPanelRoute
  IndexBeforeHotelResultsLiftRoute: typeof IndexBeforeHotelResultsLiftRoute
  IndexBeforeHotelSessionFinalWiringRoute: typeof IndexBeforeHotelSessionFinalWiringRoute
  IndexBeforeHotelSessionUiFinalRoute: typeof IndexBeforeHotelSessionUiFinalRoute
  IndexBeforeHotelSessionWiringRoute: typeof IndexBeforeHotelSessionWiringRoute
  IndexBeforeHotelTimerFixRoute: typeof IndexBeforeHotelTimerFixRoute
  IndexBeforeHotelV2Route: typeof IndexBeforeHotelV2Route
  IndexBeforeHotelVoiceErrorFixRoute: typeof IndexBeforeHotelVoiceErrorFixRoute
  IndexBeforeSerpapiRoute: typeof IndexBeforeSerpapiRoute
  IndexBeforeSidebarEditRoute: typeof IndexBeforeSidebarEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/evidence': {
      id: '/coordinator/evidence'
      path: '/evidence'
      fullPath: '/coordinator/evidence'
      preLoaderRoute: typeof CoordinatorEvidenceRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/tests': {
      id: '/coordinator/tests'
      path: '/tests'
      fullPath: '/coordinator/tests'
      preLoaderRoute: typeof CoordinatorTestsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/history/before-delete-share': {
      id: '/history/before-delete-share'
      path: '/before-delete-share'
      fullPath: '/history/before-delete-share'
      preLoaderRoute: typeof HistoryBeforeDeleteShareRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/index/before-clean-hotel-intro': {
      id: '/index/before-clean-hotel-intro'
      path: '/index/before-clean-hotel-intro'
      fullPath: '/index/before-clean-hotel-intro'
      preLoaderRoute: typeof IndexBeforeCleanHotelIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-general-sidebar': {
      id: '/index/before-general-sidebar'
      path: '/index/before-general-sidebar'
      fullPath: '/index/before-general-sidebar'
      preLoaderRoute: typeof IndexBeforeGeneralSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-conversation': {
      id: '/index/before-hotel-conversation'
      path: '/index/before-hotel-conversation'
      fullPath: '/index/before-hotel-conversation'
      preLoaderRoute: typeof IndexBeforeHotelConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-final': {
      id: '/index/before-hotel-final'
      path: '/index/before-hotel-final'
      fullPath: '/index/before-hotel-final'
      preLoaderRoute: typeof IndexBeforeHotelFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-final-2': {
      id: '/index/before-hotel-final-2'
      path: '/index/before-hotel-final-2'
      fullPath: '/index/before-hotel-final-2'
      preLoaderRoute: typeof IndexBeforeHotelFinal2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-final-fix': {
      id: '/index/before-hotel-final-fix'
      path: '/index/before-hotel-final-fix'
      fullPath: '/index/before-hotel-final-fix'
      preLoaderRoute: typeof IndexBeforeHotelFinalFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-image-fallback': {
      id: '/index/before-hotel-image-fallback'
      path: '/index/before-hotel-image-fallback'
      fullPath: '/index/before-hotel-image-fallback'
      preLoaderRoute: typeof IndexBeforeHotelImageFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-intro': {
      id: '/index/before-hotel-intro'
      path: '/index/before-hotel-intro'
      fullPath: '/index/before-hotel-intro'
      preLoaderRoute: typeof IndexBeforeHotelIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-open-final': {
      id: '/index/before-hotel-open-final'
      path: '/index/before-hotel-open-final'
      fullPath: '/index/before-hotel-open-final'
      preLoaderRoute: typeof IndexBeforeHotelOpenFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-panel': {
      id: '/index/before-hotel-panel'
      path: '/index/before-hotel-panel'
      fullPath: '/index/before-hotel-panel'
      preLoaderRoute: typeof IndexBeforeHotelPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-results-lift': {
      id: '/index/before-hotel-results-lift'
      path: '/index/before-hotel-results-lift'
      fullPath: '/index/before-hotel-results-lift'
      preLoaderRoute: typeof IndexBeforeHotelResultsLiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-session-final-wiring': {
      id: '/index/before-hotel-session-final-wiring'
      path: '/index/before-hotel-session-final-wiring'
      fullPath: '/index/before-hotel-session-final-wiring'
      preLoaderRoute: typeof IndexBeforeHotelSessionFinalWiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-session-ui-final': {
      id: '/index/before-hotel-session-ui-final'
      path: '/index/before-hotel-session-ui-final'
      fullPath: '/index/before-hotel-session-ui-final'
      preLoaderRoute: typeof IndexBeforeHotelSessionUiFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-session-wiring': {
      id: '/index/before-hotel-session-wiring'
      path: '/index/before-hotel-session-wiring'
      fullPath: '/index/before-hotel-session-wiring'
      preLoaderRoute: typeof IndexBeforeHotelSessionWiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-timer-fix': {
      id: '/index/before-hotel-timer-fix'
      path: '/index/before-hotel-timer-fix'
      fullPath: '/index/before-hotel-timer-fix'
      preLoaderRoute: typeof IndexBeforeHotelTimerFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-v2': {
      id: '/index/before-hotel-v2'
      path: '/index/before-hotel-v2'
      fullPath: '/index/before-hotel-v2'
      preLoaderRoute: typeof IndexBeforeHotelV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-hotel-voice-error-fix': {
      id: '/index/before-hotel-voice-error-fix'
      path: '/index/before-hotel-voice-error-fix'
      fullPath: '/index/before-hotel-voice-error-fix'
      preLoaderRoute: typeof IndexBeforeHotelVoiceErrorFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-serpapi': {
      id: '/index/before-serpapi'
      path: '/index/before-serpapi'
      fullPath: '/index/before-serpapi'
      preLoaderRoute: typeof IndexBeforeSerpapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index/before-sidebar-edit': {
      id: '/index/before-sidebar-edit'
      path: '/index/before-sidebar-edit'
      fullPath: '/index/before-sidebar-edit'
      preLoaderRoute: typeof IndexBeforeSidebarEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoordinatorRouteChildren {
  CoordinatorEvidenceRoute: typeof CoordinatorEvidenceRoute
  CoordinatorTestsRoute: typeof CoordinatorTestsRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
}

const CoordinatorRouteChildren: CoordinatorRouteChildren = {
  CoordinatorEvidenceRoute: CoordinatorEvidenceRoute,
  CoordinatorTestsRoute: CoordinatorTestsRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
}

const CoordinatorRouteWithChildren = CoordinatorRoute._addFileChildren(
  CoordinatorRouteChildren,
)

interface HistoryRouteChildren {
  HistoryBeforeDeleteShareRoute: typeof HistoryBeforeDeleteShareRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryBeforeDeleteShareRoute: HistoryBeforeDeleteShareRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoordinatorRoute: CoordinatorRouteWithChildren,
  HistoryRoute: HistoryRouteWithChildren,
  SettingsRoute: SettingsRoute,
  IndexBeforeCleanHotelIntroRoute: IndexBeforeCleanHotelIntroRoute,
  IndexBeforeGeneralSidebarRoute: IndexBeforeGeneralSidebarRoute,
  IndexBeforeHotelConversationRoute: IndexBeforeHotelConversationRoute,
  IndexBeforeHotelFinalRoute: IndexBeforeHotelFinalRoute,
  IndexBeforeHotelFinal2Route: IndexBeforeHotelFinal2Route,
  IndexBeforeHotelFinalFixRoute: IndexBeforeHotelFinalFixRoute,
  IndexBeforeHotelImageFallbackRoute: IndexBeforeHotelImageFallbackRoute,
  IndexBeforeHotelIntroRoute: IndexBeforeHotelIntroRoute,
  IndexBeforeHotelOpenFinalRoute: IndexBeforeHotelOpenFinalRoute,
  IndexBeforeHotelPanelRoute: IndexBeforeHotelPanelRoute,
  IndexBeforeHotelResultsLiftRoute: IndexBeforeHotelResultsLiftRoute,
  IndexBeforeHotelSessionFinalWiringRoute:
    IndexBeforeHotelSessionFinalWiringRoute,
  IndexBeforeHotelSessionUiFinalRoute: IndexBeforeHotelSessionUiFinalRoute,
  IndexBeforeHotelSessionWiringRoute: IndexBeforeHotelSessionWiringRoute,
  IndexBeforeHotelTimerFixRoute: IndexBeforeHotelTimerFixRoute,
  IndexBeforeHotelV2Route: IndexBeforeHotelV2Route,
  IndexBeforeHotelVoiceErrorFixRoute: IndexBeforeHotelVoiceErrorFixRoute,
  IndexBeforeSerpapiRoute: IndexBeforeSerpapiRoute,
  IndexBeforeSidebarEditRoute: IndexBeforeSidebarEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
