/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator.index'
import { Route as CoordinatorEvidenceRouteImport } from './routes/coordinator.evidence'
import { Route as CoordinatorTestsRouteImport } from './routes/coordinator.tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorEvidenceRoute = CoordinatorEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorTestsRoute = CoordinatorTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => CoordinatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/coordinator/evidence': typeof CoordinatorEvidenceRoute
  '/coordinator/tests': typeof CoordinatorTestsRoute
  '/coordinator/': typeof CoordinatorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/coordinator/evidence': typeof CoordinatorEvidenceRoute
  '/coordinator/tests': typeof CoordinatorTestsRoute
  '/coordinator': typeof CoordinatorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/coordinator/evidence': typeof CoordinatorEvidenceRoute
  '/coordinator/tests': typeof CoordinatorTestsRoute
  '/coordinator/': typeof CoordinatorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coordinator'
    | '/history'
    | '/settings'
    | '/coordinator/evidence'
    | '/coordinator/tests'
    | '/coordinator/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/settings'
    | '/coordinator/evidence'
    | '/coordinator/tests'
    | '/coordinator'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coordinator'
    | '/history'
    | '/settings'
    | '/coordinator/evidence'
    | '/coordinator/tests'
    | '/coordinator/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoordinatorRoute: typeof CoordinatorRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/evidence': {
      id: '/coordinator/evidence'
      path: '/evidence'
      fullPath: '/coordinator/evidence'
      preLoaderRoute: typeof CoordinatorEvidenceRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/tests': {
      id: '/coordinator/tests'
      path: '/tests'
      fullPath: '/coordinator/tests'
      preLoaderRoute: typeof CoordinatorTestsRouteImport
      parentRoute: typeof CoordinatorRoute
    }
  }
}

interface CoordinatorRouteChildren {
  CoordinatorEvidenceRoute: typeof CoordinatorEvidenceRoute
  CoordinatorTestsRoute: typeof CoordinatorTestsRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
}

const CoordinatorRouteChildren: CoordinatorRouteChildren = {
  CoordinatorEvidenceRoute: CoordinatorEvidenceRoute,
  CoordinatorTestsRoute: CoordinatorTestsRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
}

const CoordinatorRouteWithChildren = CoordinatorRoute._addFileChildren(
  CoordinatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoordinatorRoute: CoordinatorRouteWithChildren,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
